/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.SwingConstants;
import comunicacaoJava.ComunicacaoSerial;
import processo.*;
import java.util.TimerTask;
import java.util.Timer;

/**
 *
 * @author henre
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        //tq1.setOrientation(SwingConstants.VERTICAL);
       // tq1.setSize(40, 40);
        tq1View.setValue(50);
        inicializarPlanta();
    }
    
    //Codigo de COntrole da cerveja
    //========================================================================
    
    ComunicacaoSerial comunicacao = new ComunicacaoSerial(Util.Configuracoes.portaSerial);
    Tanque HLT, MLT, BK;
    Temperaturas temperaturas;
    Vazoes vazoes;
    Timer timerUpdate;
    private void inicializarPlanta(){
        
        try {
            comunicacao.conectar();
	} catch (Exception e) {
	
            e.printStackTrace();
	}
        
        temperaturas = new Temperaturas(3);
        temperaturas.setComunicacao(comunicacao);
        vazoes = new Vazoes();
        vazoes.setComunicacao(comunicacao);
        HLT = new Tanque(vazoes.getVazao(0),vazoes.getVazao(1),temperaturas.getTemperatura(0),0,1,1);
        HLT.setComunicacao(comunicacao);
        
        
        
        //=====Timer======
        timerUpdate = new Timer();
	timerUpdate.scheduleAtFixedRate(new RelogioUpdate(), 2000, 1000);
        
    }
    
    
    class RelogioUpdate extends TimerTask{


		@Override
		public void run() {
			// TODO Auto-generated method stub
			try {
			//valvulas.updateStatus();

			//vazoes.updateVazoes();
			System.out.println("Updating");
			temperaturas.updateTemperaturas();
			//resistencias.updateResistencias();
			//bomba.updateStatus();
			txtVolTq1.setText(String.valueOf(HLT.getLevel())+"l");
			txtTempTq1.setText(String.valueOf(HLT.getTemperatura())+"oC");
			//temperaturaTQ2.setText(String.valueOf(temperaturas.getTemperatura(1).getTemperatura()));
			//temperaturaTQ3.setText(String.valueOf(temperaturas.getTemperatura(2).getTemperatura()));
			//medidorvazao1.setText(String.valueOf(vazoes.getVazao(0).getInstantaneo())+"l/m");
			//medidorvazao2.setText(String.valueOf(vazoes.getVazao(1).getInstantaneo())+"l/m");
			//medidorvazao3.setText(String.valueOf(vazoes.getVazao(2).getInstantaneo())+"l/m");

			//resistencia1.setStroke(resistencias.getResistencia(0).getColorStatus());
			//resistencia2.setStroke(resistencias.getResistencia(1).getColorStatus());
			//resistencia3.setStroke(resistencias.getResistencia(2).getColorStatus());

			//valorresistencia1.setText(String.valueOf((resistencias.getResistencia(0).getPotencia()/255)*100));
			//valorresistencia2.setText(String.valueOf((resistencias.getResistencia(1).getPotencia()/255)*100));
			//valorresistencia3.setText(String.valueOf((resistencias.getResistencia(2).getPotencia()/255)*100));
			//bombaCirculoInterno.setFill(bomba.getColorStatus());
			//calcAlturaTanques2(tq1_externo, tq1_interno, HLT);
			//calcAlturaTanques2(tq2_externo, tq2_interno, MLT);
			//calcAlturaTanques2(tq3_externo, tq3_interno, BK);
			//if (etapas.etapacorrente != null)
			//	etapas.etapacorrente.verificarExecutando();
			
			//Status do sistema
			//if (HLT.Aquecendo()) {
			//	statusAquecimento.setText(HLT.getMsgStatus());
			//	tempo.setText(String.valueOf(HLT.getTempoDecorrido()));
			
			//}
			//medidorvazao4.setText(String.valueOf(vazoes.getVazao(3))+"l/m");
			//System.out.println(String.valueOf(vazoes.getVazao(0))+"l/m");
			}
			catch (Exception e) {
				// TODO: handle exception
			}
		}


	}

    ///=======================================================================

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProcesso = new javax.swing.JPanel();
        tq1View = new javax.swing.JProgressBar();
        panelVariaveisTq1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVolTq1 = new javax.swing.JTextField();
        txtTempTq1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cerveja");
        setPreferredSize(new java.awt.Dimension(800, 480));
        setSize(new java.awt.Dimension(800, 480));

        panelProcesso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tq1View.setOrientation(1);
        panelProcesso.add(tq1View, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 30, 103, 134));

        panelVariaveisTq1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Volume:");

        jLabel2.setText("Temperatura:");

        txtVolTq1.setText("jTextField1");

        txtTempTq1.setText("jTextField2");

        javax.swing.GroupLayout panelVariaveisTq1Layout = new javax.swing.GroupLayout(panelVariaveisTq1);
        panelVariaveisTq1.setLayout(panelVariaveisTq1Layout);
        panelVariaveisTq1Layout.setHorizontalGroup(
            panelVariaveisTq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVariaveisTq1Layout.createSequentialGroup()
                .addGroup(panelVariaveisTq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVariaveisTq1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVolTq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelVariaveisTq1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTempTq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelVariaveisTq1Layout.setVerticalGroup(
            panelVariaveisTq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVariaveisTq1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVariaveisTq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVolTq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVariaveisTq1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTempTq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProcesso.add(panelVariaveisTq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/valve.png"))); // NOI18N
        panelProcesso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 223, 34, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fundo.png"))); // NOI18N
        panelProcesso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelProcesso;
    private javax.swing.JPanel panelVariaveisTq1;
    private javax.swing.JProgressBar tq1View;
    private javax.swing.JTextField txtTempTq1;
    private javax.swing.JTextField txtVolTq1;
    // End of variables declaration//GEN-END:variables
}
